######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 28 15:11:34 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
CONFIG -= moc
INCLUDEPATH += /usr/include/qwt /usr/include/qwt5
LIBS += -lqwt

# Input
HEADERS += plotter.h multiPlotter.h serialLib/serialLinux.h
SOURCES += main.cpp plotter.cpp multiPlotter.cpp serialLib/serialLinux.cpp
